spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=worker-wallet-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.properties.schema.registry.url=http://schema-registry:8081
keycloak.url.realm=http://keycloak:8080/realms/recargapay_wallet_test
client.id= api-wallet
logging.file.path=/var/log/worker-wallet
logging.file.name=/var/log/worker-wallet/application.log
logging.level.root=INFO
server.port=8085