server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: api-wallet
    static_configs:
      - targets:
          - localhost
        labels:
          job: api-wallet
          __path__: /var/log/api-wallet/*.log

  - job_name: worker-wallet
    static_configs:
      - targets:
          - localhost
        labels:
          job: worker-wallet
          __path__: /var/log/worker-wallet/*.log
