KafkaServer {
    org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
    oauth.token.endpoint.uri="http://keycloak:8080/realms/recargapay_wallet_test/protocol/openid-connect/token"
    oauth.client.id="kafka"
    oauth.client.secret="l3m0gaVMmrt3215qweCDssAasQFwTXe0Jnx"
    oauth.scope="email profile";
};
