# Keycloak Configuration
keycloak.realm=recargapay_wallet_test
keycloak.auth-server-url=http://keycloak:8080
keycloak.resource=api-wallet
keycloak.bearer-only=true

logging.file.path=/var/log/api-wallet
logging.file.name=/var/log/api-wallet/application.log
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG


server.port=8084


spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}

